- 👋 ola eu me chamo brunino-da-z3
- 👀 I’m interested in aprender a criar ...
- 🌱 I’m currently learning ...
- 💞️ I’m looking to collaborate on ...
- 📫 How to reach me ...

<!---
brunino-da-z3/brunino-da-z3 is a ✨ special ✨ repository because its `README.md` (this file) appears on your GitHub profile.
You can click the Preview link to take a look at your changes.
--->
